CREATE TABLE 'Devices' (
	'Id'			INTEGER PRIMARY KEY AUTOINCREMENT,
	'Deleted'		INTEGER NOT NULL DEFAULT 0,
	'Enabled'		INTEGER NOT NULL DEFAULT 1,
	'DeviceName'	TEXT NOT NULL,
	'DeviceKey'		TEXT NOT NULL
);